version: '3.9'
services:
  webserver:
    build: http/
    labels:
      ho.ctf.cyrhades: webserver
    restart: always
    ports:
      - "80:80"
    container_name: ho-webserver
    command: npm start